# Markdownlint configuration
extends: null
rules:
  # Line length
  MD013:
    line_length: 120
    code_blocks: false
    tables: false
    headings: false
  
  # Trailing spaces
  MD009:
    br_spaces: 2
    list_item_empty_lines: false
  
  # Multiple consecutive blank lines
  MD012:
    maximum: 2
  
  # Line length in code blocks
  MD013: false
  
  # Inline HTML
  MD033:
    allowed_elements: [br, sub, sup, kbd, details, summary]
  
  # Emphasis used instead of a heading
  MD036: false
  
  # Files should end with a single newline character
  MD047: true
  
  # Code fence style
  MD048:
    style: backtick
  
  # Proper names should have the correct capitalization
  MD044:
    names: [GitHub, PyPI, API, JSON, YAML, CLI, CI/CD, HTTP, URL]
    code_blocks: false
