name: CI Pipeline
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      # ❌ Missing Node.js caching opportunity
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Install dependencies
        run: npm ci
      
      # ❌ Sequential testing (could be parallelized)
      - name: Unit tests
        run: npm run test:unit
      
      - name: Integration tests  
        run: npm run test:integration
      
      - name: Lint
        run: npm run lint