name: Basic Java CI
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      
      # ❌ Missing Maven dependency caching
      - name: Build with Maven
        run: mvn clean compile
      
      - name: Run tests
        run: mvn test
      
      - name: Run integration tests
        run: mvn verify -P integration-tests

  # ❌ Separate job repeating Maven setup
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      
      # ❌ Maven dependencies downloaded again
      - name: Package application
        run: mvn clean package -DskipTests
      
      # ❌ Uploads entire target directory
      - name: Upload JAR files
        uses: actions/upload-artifact@v3
        with:
          name: jar-artifacts
          path: target/